### ISSUE TITLE
[UIKit] Show sender name for voice and image message

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat-SDK-iOS#102]

**Comment by ben181231** [comment]
I found that the current voice / image message do have sender name. However the library won't show the sender name when it is the same as the previous message (even it is separated into 2 time sections).

![screenshot 1](https://user-images.githubusercontent.com/3863953/32048482-3993e884-ba7c-11e7-970b-a76cfa62f005.jpeg)

![screenshot 2](https://user-images.githubusercontent.com/3863953/32048574-88820868-ba7c-11e7-83c1-63d23f1007ac.jpeg)

@carmenlau do we need to change to this logic?

**Comment by carmenlau** [comment]
Oh, maybe just keep as it first if it is not bug. I think we will need to allow user to config it, but it should be the customization part. Close it for now, thanks @ben181231 :)
