### ISSUE TITLE
[UIKit] Configuration of Conversation View

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/chat-SDK-iOS#103]
I'm aggregating the settings of Conversation View here. 

I think we need to design a way so that configuration is easy to set. Top of my head it could be done by:

1. Constructor configurations + Setter
2. App Delegate.

I think different config might be better to use a different way to configure? Or we should just use app delegate? (However, I think it is weird to use app delegate to set simple things like the color?)

Also, don't assume all Conversation View in the apps have the same setting. (e.g. Users might want Read by enabled only for certain users).

Anyway, here are a list:

## Feature Enable
* Disable / Enable Voice Message
* Disable / Enable Sending Attachment
* Disable / Enable Sending Camera Images
* Disable / Enable Read Status
* Disable / Enable Typing Indicator

## UI Customization
* Bubble background color
* Bubble text color
* Conversion background color
* Conversion background images
* Show / Hide X Sender / Receiver avatar
* Text Area Background Color
* Icons of Attachment, Camera, and Voice Message
* Copywriting Customization #39 

## Data Customization
* User avatar #95 
* Display name of user

## Behaviour Customization
* Show Group Title or Other Username's as Group name #80 

## Event Hook Callback #148 
* New Message in Conversation View
* Updated Message in Conversation View
* Before / After Message Send
* Message Send Failed
* Disconnected
* Connected

**Comment by carmenlau** [comment]
## Feature Enable
- [x] Disable / Enable Voice Message
- [x]  Disable / Enable Sending Camera Images
- [ ] ~~Disable / Enable Sending Attachment~~
- [x]  Disable / Enable Read Status
- [x] Disable / Enable Typing Indicator

## UI Customization
- [x] Bubble incoming background color
- [x] Bubble incoming text color
- [x] Bubble incoming voice play button color
- [x] Bubble outgoing background color
- [x] Bubble outgoing text color
- [x] Bubble outgoing status text color
- [x] Bubble outgoing voice play button color
- [x] Timestamp section separator text color
- [x] Conversion background color
- [x] Conversion background images (UIImage)
- [x] Conversion background images (URL)
- [x] Show Group Title or Other Username's as Group name #80 
- [ ] ~~Text Area Background Color~~
- [ ] ~~Icons of Attachment, Camera, and Voice Message~~

## Behaviour Customization
- [x] Copywriting Customization #39 

## Event Hook Callback 
#148
- [ ] New Message in Conversation View
- [ ] Updated Message in Conversation View
- [ ] Before / After Message Send
- [ ] Message Send Failed
- [ ] Disconnected
- [ ] Connected
