### ISSUE TITLE
[UIKit] avatarHidden = true making the avatar flash on enter conversation view

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat-SDK-iOS#133]
SKYChatConversationView.appearance().avatarHidden = true making the avatar flash on enter conversation view.

https://youtu.be/2eZnr_wRns0

**Comment by ben181231** [comment]
After some investigation, this is due to the reason that values in `UIAppearance` proxy are only available after the view is attached to screen. So unless we gave up using `UIAppearance`, we cannot solve this easily.
