### ISSUE TITLE
The chat view shifted to the top crash the layout when back from another view controller

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat-SDK-iOS#143]
Steps:
Go to Chat message page
Click to open the keyboard
Navigation controller push to another view
Click Backward button to go back to Chat message page

Video
https://youtu.be/Z8ZaeOfLo9U

**Comment by ben181231** [comment]
@carmenlau Verified with @wallacesky. I cannot reproduce it on sample project. 
But I found another minor issue when pushing a new view controller and pop back.
Going to fix it in this issue.

**Comment by carmenlau** [comment]
Maybe after we merged your fix, let @wallacesky to update uikit in his project and check again.

Thanks @ben181231

**Comment by wallacesky** [comment]
Thanks for your effort. I will report if I have any new findings.

**Comment by wallacesky** [comment]
@ben181231 @carmenlau 
FYI
I fixed my navigation bar moving up issue by disabling the IQKeyboardManager in my customised `SKYChatConversationViewController`
IQKeyboardManager should not be applied with `SKYKitChatUI` otherwise the change of keyboard frame height will lead some wire UI issues

**Comment by ben181231** [comment]
@wallacesky 

Maybe it is due to the conflict of `JSQMessagesKeyboardController` and `IQKeyboardManager`. [This PR](https://github.com/SkygearIO/chat-SDK-iOS/pull/146) will remove some functionality of `JSQMessagesKeyboardController`. See it can fix the conflict.
