### ISSUE TITLE
RLMException thrown by realm 

### ISSUE THREAD

**Issue by wallacesky** [SkygearIO/chat-SDK-iOS#149]
# Situation
Step of crash:
1. Fresh install
2. Fetch a list of `SKYConversation` by calling `chatExtension.fetchConversations(...)`
3. Initialize `SKYChatConversationViewController` and assign the `SKYConverstaion` instance
```
let vc = SKYChatConversationViewController()
vc.conversation = conversation // conversation object create from chat sdk
self.navigationController?.pushViewController(vc, animated: true)
```
4. Push the view controller which leads to app crash, exception logs is provided below

```
*** Terminating app due to uncaught exception 'RLMException', reason: 'Realm accessed from incorrect thread.'
*** First throw call stack:
(0x181a761c0 0x1804b055c 0x10331834c 0x103219e28 0x1032198e0 0x103207664 0x103e3e074 0x103e3da24 0x103e43874 0x103e9901c 0x103e99344 0x103e7a390 0x103e7a568 0x1878e7ee4 0x1878e7c5c 0x187a70190 0x187988858 0x1879884c0 0x187988424 0x1878cd220 0x184d8d188 0x184d81e64 0x184d81d24 0x184cfe7ec 0x184d25c58 0x1878c28f0 0x181a237dc 0x181a2140c 0x181a2189c 0x181950048 0x1833d6198 0x18793b2fc 0x187936034 0x1000b0338 0x1809345b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

However, the next app launch and rerun from step 2 to 4. Everything is going alright without any errors. 

connects #166

**Comment by ben181231** [comment]
@wallacesky 

I cannot reproduce using the provided steps. I have verified:

1. It works when directly initiating a `SKYChatConversationViewController` and push it.

```
    let vc = SKYChatConversationViewController()
    vc.conversation = conversation
    self.navigationController?.pushViewController(vc, animated: true)
```

2. The fetch API (`skygear.chatExtension.fetchConversations(...)`) involves the callback in main thread.

**Comment by wallacesky** [comment]
@ben181231 
![screen shot 2018-01-05 at 12 10 38 pm](https://user-images.githubusercontent.com/25768406/34595299-df32d0bc-f211-11e7-8369-e7b00d5b0599.png)
