### ISSUE TITLE
[Urgent] Please fix your published fork of JSQMessagesViewController.

### ISSUE THREAD

**Issue by jessesquires** [SkygearIO/chat-SDK-iOS#193]
Hi @cheungpat 

It appears that you've renamed my pod and published it here: https://github.com/SkygearIO/JSQMessagesViewController/commit/b9288b8480dc6d78e4c169413fdaa6097765fe89

However, you didn't update the author credentials, so now it's attributed to me.
https://twitter.com/CocoaPodsFeed/status/960449550132629504

**I do not want your forked attributed to me.** 

Steps to fix:
1. Run `pod trunk delete` to delete this pod from the main CP repo
2. Update the spec to **remove** my name in `s.author`. Also remove `s.homepage`, `s.social_media_url`, and `s.screenshots`. Put your own name, etc. in here
3. Re-publish the pod

Also see my comment here:
https://github.com/SkygearIO/JSQMessagesViewController/commit/b9288b8480dc6d78e4c169413fdaa6097765fe89#commitcomment-27355635

**Comment by jessesquires** [comment]
If you could fix this ASAP, I'd really appreciate it.

**Comment by cheungpat** [comment]
@jessesquires Really sorry that I missed that. Will fix that ASAP.

**Comment by jessesquires** [comment]
Thank you so much @cheungpat ! Let me know if you need any help. 😊

**Comment by jessesquires** [comment]
Hey @cheungpat -- any updates here? 😄

**Comment by carmenlau** [comment]
@jessesquires We changed it already:)

**Comment by jessesquires** [comment]
Thanks @cheungpat @carmenlau !
