### ISSUE TITLE
[Critical, Chat] App crash after pressing "resend" or "delete" for failed sending message

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat-SDK-iOS#208]
- Device: iPhone SE (10.3.3)

**Comment by ben181231** [comment]
I cannot reproduce using Skygear Chat v1.2.0-alpha.7 and the current master branch. May I have more details on this issue?

**Comment by carmenlau** [comment]
@ben181231 Would like to know are you testing it in iOS 10.3.3?

**Comment by carmenlau** [comment]
I cannot reproduce it either

**Comment by carmenlau** [comment]
I will close this as cannot reproduce, will open it again when it occurs
