### ISSUE TITLE
[Major, Chat] Incomplete swipe back will lead to broken layout

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat-SDK-iOS#211]
- Device:   iPhone 6s (11.2.1)

## Steps to reproduce:
1. go into chat detail page
2. send a message
3. swipe back (half of the page) then release (stay in chat detail page)
4. see that Extra white space and icon misplaced

![img_1718](https://user-images.githubusercontent.com/388892/37070261-9cd812bc-21f1-11e8-82f9-16a31080866a.png)

**Comment by ben181231** [comment]
After investigation, found out that the conversation view is embedded in UITabBarController and the hidden state of the tab bar is not handled very well.

This issue should be fixed after [the commit](https://github.com/skygear-demo/SkygearChat-iOS-Demo/commit/634e11a) in demo project.
