### ISSUE TITLE
UIKit event hooks issues

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat-SDK-iOS#218]
- should be `didFetchMessages` instead of `didFetchedMessages`
- should update `didFetchParticipants` with `isCached`
- `didFetchParticipants` called twice when I enter the conversation view, is it expected?
- `didFetchedMessages` `isCached=true` are called twice and `isCached=false` called once, need check again and see if hooks are calling in right places. In my testing, the events are calling this way:
    - [Event]didFetchedMessages isCached=YES
    - [Event]startFetchingMessages
    - [Event]didFetchedMessages isCached=YES
    - [Event]didFetchedMessages isCached=NO
- When receive 1 new message got following events
    - [Event]didReceiveMessage <SKYMessage: 0x1c083bc40>
    - [Event]didFetchedMessages isCached=NO
    - [Event]didUpdateMessage <SKYMessage: 0x1c0232e40>
    - [Event]didUpdateMessage <SKYMessage: 0x1c083d660>
- `pubsubDidDisconnectInConversationViewController` is not fire when I switch to airplane mode

**Comment by cheungpat** [comment]
hi @carmenlau I am looking at the PR on #222 but I am not sure if it has fixed the thing you mentioned, especially with pubsub disconnecting and the number of times fetch participant is called.
