### ISSUE TITLE
JSQMessagesViewController is officially deprecated

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/chat-SDK-iOS#47]
https://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Also keep track of https://github.com/jessesquires/JSQMessagesViewController/issues/2159

Option 1: Switch to another ViewController
Option 2: Fork and maintain our own version

**Comment by carmenlau** [comment]
Duplicated #119
