### ISSUE TITLE
[UIKit] Support send photo

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat-SDK-iOS#63]
Need multiple photo support

- [ ] Send a photo as a message attachment
  - [ ] Encode the photo that is ready to display
  - [ ] The encoding can be configurable
- [ ] Display photo inline

**Comment by Steven-Chan** [comment]
https://github.com/SkygearIO/skygear-SDK-iOS/issues/133

**Comment by Steven-Chan** [comment]
https://github.com/SkygearIO/chat-SDK-iOS/issues/70
