### ISSUE TITLE
Support automaticallyMarkMessageAsDelivered

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/chat-SDK-iOS#77]
Support automaticallyMarkMessageAsDelivered
Similar to http://cocoadocs.org/docsets/SKYKitChat/0.0.1/Classes/SKYChatExtension.html#//api/name/markDeliveredMessages:completion:NS_SWIFT_NAME:

**Comment by carmenlau** [comment]
We supported it already 
https://github.com/SkygearIO/chat-SDK-iOS/blob/27c5d0172cf245a93a91142b71cd0aa1f168a307/SKYKitChat/Classes/Core/SKYChatExtension.m#L581
