### ISSUE TITLE
Strange spacing at the top

### ISSUE THREAD

**Issue by mayyuen318** [SkygearIO/chat-SDK-iOS#81]
<img width="288" alt="screen shot 2017-10-17 at 12 24 26 am" src="https://user-images.githubusercontent.com/7130966/31624208-78aeba08-b2d4-11e7-8bde-9a92a1bf77d9.png">

There is a sudden drop (see attachment) after I open a group conversation.

**Comment by howawong** [comment]
@mayyuen318  I could not reproduce it.... How did you reproduce the bug?

**Comment by mayyuen318** [comment]
I wasn't able to reproduce again when I used it again.  Let's close this first.
