### ISSUE TITLE
Scaffolding does not work because 0.0.2 has a dependency on v0 of Skygear SDK

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/chat-SDK-iOS#88]
Hi,

So I am looking at https://github.com/SkygearIO/skygear-Scaffolding-iOS/issues/13 and realised that the version 0.0.2 (Cocoapods released version) have a [dependency on v0 SDK](https://github.com/SkygearIO/chat-SDK-iOS/blob/0.0.2/SKYKitChat.podspec). Since the current master has dependency on the v1 version instead, releasing a new version will fix the problem with the scaffolding.

Also suggesting we change `SKYKitChat.podspec` to specify dependency as `~> 1.1` instead of `~> 1.1.0` because we probably want the scaffolding to automatically install 1.2 when it comes out. See also: [Podspec Syntax Reference: dependency](https://guides.cocoapods.org/syntax/podspec.html#dependency)

Not sure who to assign so I am assigning @carmenlau who are welcome to assign someone else to the task.

**Comment by carmenlau** [comment]
We released v1.1 of chat sdk yesterday. I tested creating new scaffolding project, but I still downloading v0.0.2 sdk. No idea why it doesn't download the latest, need further check.

**Comment by carmenlau** [comment]
Verified in SkygearIO/skygear-Scaffolding-iOS#13
