### ISSUE TITLE
[UIKit] Allow support config user fields for display name and avatar

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/chat-SDK-iOS#95]

**Comment by chpapa** [comment]
@carmenlau how would the support be like? I suppose it should be like:

At `SKYChatConversationViewController()`, there will be a setting in the constructor to:

1. Specific avatar by:
    1. Which field in the User Record is the Asset field to the avatar, or
    1. Which field in the User Record is the URL to the avatar, or
    1. AppDelegate to resolve the Avatar, from the Message object
1. Specific a default avatar, which will show if the field in User Record is empty or null,
    1. An Image object in native platform, or
    1. Default generator pick two letters in the username to show an icon like "BC" (Ben Cheng)
    1. AppDelegate are supposed to handle default avatar on its own.

**Comment by carmenlau** [comment]
- UIAppearance
    - avatar
    - avatarType
- delegate
    - accept conversation, message, author
    - return View

**Comment by rickmak** [comment]
Improved list of config after offline discussion (@carmenlau, @howawong, @ben181231, @Steven-Chan, @cheungpat )

- UI Customization
  - Background color
  - Initial text color
  - Sender text color
- Data Customization
    - avatar
    - avatarType
    - username field
    - Show hide Sender / Receiver
- delegate
    - accept conversation, message, author -> return View (Example rainbow bg color in group chat)
    - Show hide Sender / Receiver

**Comment by carmenlau** [comment]
@ben181231 I did a Basic estimation for the breakdown, feel free to change it and check if it makes sense?
- [8] UI Customization
    - Fork jsqmessagesviewcontroller and support ui appearance class
    - Background color
    - Initial text color
    - Sender text color
    - Show hide Sender / Receiver avatar
- [3] Data Customization
    - avatarField 
    - avatarType (initial/image)
    - username field
- [5] delegate
    - accept conversation, message, author -> return View (Example rainbow bg color in group chat)
    - Show hide Sender / Receiver

**Comment by carmenlau** [comment]
check for https://github.com/MessageKit/MessageKit

**Comment by ben181231** [comment]
- Customization using `SKYChatUIModelCustomization` in `AppDelegate`:

```swift
SKYChatUIModelCustomization.default()
    .update(userNameField: "name")
    .update(userAvatarField: "profile_pic")
```

- Customization using `SKYChatConversationView.appearance()` in `AppDelegate`:

```swift
SKYChatConversationView.appearance().avatarBackgroundColor
    = UIColor(red: 0, green: 0.4745, blue: 0.8235, alpha: 1.0)
SKYChatConversationView.appearance().avatarTextColor = UIColor.black
SKYChatConversationView.appearance().messageSenderTextColor = UIColor.black
SKYChatConversationView.appearance().avatarType = .image
SKYChatConversationView.appearance().avatarHiddenForOutgoingMessages = true
SKYChatConversationView.appearance().avatarHiddenForIncomingMessages = false
```

**Comment by rickmak** [comment]
`SKYChatConversationView.appearance().avatarHidden = true` making the avatar flash on enter conversation list. is it a know issue?

https://youtu.be/2eZnr_wRns0

**Comment by carmenlau** [comment]
no, opened an issue for that https://github.com/SkygearIO/chat-SDK-iOS/issues/133
